# -*- coding: utf-8 -*-
"""tes kepribadiaan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qKMHTPSKz0ydpqexYyGWUYT_gpMsoo0t
"""

def kalkulator_kepribadian():
    """
    Kalkulator kepribadian sederhana berdasarkan preferensi ala MBTI.
    """
    print("Selamat datang di Kalkulator Kepribadian Sederhana!")
    print("Mari kita tentukan preferensi kepribadian Anda.")
    print("Pilih 'A' atau 'B' untuk setiap pertanyaan yang paling sesuai dengan Anda.")
    print("-" * 60)

    # Inisialisasi skor untuk setiap dimensi
    skor = {
        'E': 0, 'I': 0,
        'S': 0, 'N': 0,
        'T': 0, 'F': 0,
        'J': 0, 'P': 0
    }

    # Pertanyaan untuk dimensi Ekstroversi (E) vs. Introversi (I)
    print("\n--- Dimensi: Ekstroversi (E) vs. Introversi (I) ---")
    # Pertanyaan 1
    while True:
        jawaban = input("1. Setelah seharian bekerja/beraktivitas, Anda merasa lebih berenergi jika:\n   A) Bersosialisasi dengan teman atau pergi ke pesta.\n   B) Menghabiskan waktu sendirian atau dengan kelompok kecil yang akrab.\nJawaban (A/B): ").strip().upper()
        if jawaban == 'A':
            skor['E'] += 1
            break
        elif jawaban == 'B':
            skor['I'] += 1
            break
        else:
            print("Pilihan tidak valid. Silakan masukkan 'A' atau 'B'.")

    # Pertanyaan 2
    while True:
        jawaban = input("2. Dalam percakapan, Anda cenderung:\n   A) Berbicara dengan lantang dan berbagi banyak ide.\n   B) Mendengarkan lebih banyak dan berpikir sebelum berbicara.\nJawaban (A/B): ").strip().upper()
        if jawaban == 'A':
            skor['E'] += 1
            break
        elif jawaban == 'B':
            skor['I'] += 1
            break
        else:
            print("Pilihan tidak valid. Silakan masukkan 'A' atau 'B'.")

    # Pertanyaan untuk dimensi Sensing (S) vs. Intuition (N)
    print("\n--- Dimensi: Sensing (S) vs. Intuition (N) ---")
    # Pertanyaan 3
    while True:
        jawaban = input("3. Saat belajar atau mengerjakan sesuatu, Anda lebih suka:\n   A) Fakta konkret dan detail yang jelas.\n   B) Konsep abstrak, teori, dan kemungkinan masa depan.\nJawaban (A/B): ").strip().upper()
        if jawaban == 'A':
            skor['S'] += 1
            break
        elif jawaban == 'B':
            skor['N'] += 1
            break
        else:
            print("Pilihan tidak valid. Silakan masukkan 'A' atau 'B'.")

    # Pertanyaan 4
    while True:
        jawaban = input("4. Anda lebih tertarik pada:\n   A) Apa yang nyata dan dapat diamati.\n   B) Makna tersembunyi dan pola di balik sesuatu.\nJawaban (A/B): ").strip().upper()
        if jawaban == 'A':
            skor['S'] += 1
            break
        elif jawaban == 'B':
            skor['N'] += 1
            break
        else:
            print("Pilihan tidak valid. Silakan masukkan 'A' atau 'B'.")

    # Pertanyaan untuk dimensi Thinking (T) vs. Feeling (F)
    print("\n--- Dimensi: Thinking (T) vs. Feeling (F) ---")
    # Pertanyaan 5
    while True:
        jawaban = input("5. Ketika membuat keputusan penting, Anda cenderung:\n   A) Menganalisis secara logis, objektif, dan mempertimbangkan pro & kontra.\n   B) Mempertimbangkan nilai-nilai pribadi, dampak pada orang lain, dan harmoni.\nJawaban (A/B): ").strip().upper()
        if jawaban == 'A':
            skor['T'] += 1
            break
        elif jawaban == 'B':
            skor['F'] += 1
            break
        else:
            print("Pilihan tidak valid. Silakan masukkan 'A' atau 'B'.")

    # Pertanyaan 6
    while True:
        jawaban = input("6. Anda lebih cenderung memberikan kritik yang:\n   A) Jujur dan blak-blakan, fokus pada kebenaran dan efisiensi.\n   B) Lembut dan mempertimbangkan perasaan orang lain, fokus pada menjaga hubungan.\nJawaban (A/B): ").strip().upper()
        if jawaban == 'A':
            skor['T'] += 1
            break
        elif jawaban == 'B':
            skor['F'] += 1
            break
        else:
            print("Pilihan tidak valid. Silakan masukkan 'A' atau 'B'.")

    # Pertanyaan untuk dimensi Judging (J) vs. Perceiving (P)
    print("\n--- Dimensi: Judging (J) vs. Perceiving (P) ---")
    # Pertanyaan 7
    while True:
        jawaban = input("7. Anda lebih suka:\n   A) Merencanakan segala sesuatu dengan baik dan mengikuti jadwal.\n   B) Bersifat spontan, fleksibel, dan membiarkan opsi tetap terbuka.\nJawaban (A/B): ").strip().upper()
        if jawaban == 'A':
            skor['J'] += 1
            break
        elif jawaban == 'B':
            skor['P'] += 1
            break
        else:
            print("Pilihan tidak valid. Silakan masukkan 'A' atau 'B'.")

    # Pertanyaan 8
    while True:
        jawaban = input("8. Ketika ada deadline, Anda cenderung:\n   A) Menyelesaikan pekerjaan jauh sebelum deadline.\n   B) Bekerja lebih baik di bawah tekanan deadline mendekat.\nJawaban (A/B): ").strip().upper()
        if jawaban == 'A':
            skor['J'] += 1
            break
        elif jawaban == 'B':
            skor['P'] += 1
            break
        else:
            print("Pilihan tidak valid. Silakan masukkan 'A' atau 'B'.")

    print("-" * 60)
    print("\nHasil Preferensi Kepribadian Anda:")

    # Menentukan preferensi akhir
    tipe_kepribadian = ""

    # Dimensi E vs I
    if skor['E'] > skor['I']:
        tipe_kepribadian += "E"
        deskripsi_ei = "Anda cenderung lebih **Ekstrover**, mendapatkan energi dari interaksi sosial dan dunia luar."
    else:
        tipe_kepribadian += "I"
        deskripsi_ei = "Anda cenderung lebih **Introver**, mendapatkan energi dari refleksi diri dan waktu sendirian."

    # Dimensi S vs N
    if skor['S'] > skor['N']:
        tipe_kepribadian += "S"
        deskripsi_sn = "Anda cenderung lebih **Sensing**, fokus pada fakta, detail, dan apa yang nyata."
    else:
        tipe_kepribadian += "N"
        deskripsi_sn = "Anda cenderung lebih **Intuitive**, fokus pada konsep, pola, dan kemungkinan masa depan."

    # Dimensi T vs F
    if skor['T'] > skor['F']:
        tipe_kepribadian += "T"
        deskripsi_tf = "Anda cenderung lebih **Thinking**, membuat keputusan berdasarkan logika dan objektivitas."
    else:
        tipe_kepribadian += "F"
        deskripsi_tf = "Anda cenderung lebih **Feeling**, membuat keputusan berdasarkan nilai-nilai dan dampak pada orang lain."

    # Dimensi J vs P
    if skor['J'] > skor['P']:
        tipe_kepribadian += "J"
        deskripsi_jp = "Anda cenderung lebih **Judging**, suka terencana, teratur, dan membuat keputusan."
    else:
        tipe_kepribadian += "P"
        deskripsi_jp = "Anda cenderung lebih **Perceiving**, suka spontan, fleksibel, dan menjaga opsi tetap terbuka."

    print(f"Tipe Kepribadian Anda (Sederhana): **{tipe_kepribadian}**")
    print("\n--- Deskripsi Preferensi Anda ---")
    print(f"**E/I:** {deskripsi_ei}")
    print(f"**S/N:** {deskripsi_sn}")
    print(f"**T/F:** {deskripsi_tf}")
    print(f"**J/P:** {deskripsi_jp}")

    print("\n*Penting: Kalkulator ini adalah penyederhanaan dan bukan alat diagnostik MBTI yang valid secara profesional. Kepribadian Anda jauh lebih kompleks dari sekadar empat huruf ini!*")
    print("Untuk pemahaman lebih mendalam, konsultasikan dengan psikolog atau ikuti tes kepribadian yang tervalidasi.")

# Jalankan kalkulator
if __name__ == "__main__":
    kalkulator_kepribadian()