# -*- coding: utf-8 -*-
"""kombinasi (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NU34QS9RFMiePd8T5ErGYPre5gZJUykh
"""

import streamlit as st
from itertools import product

st.title("Virtual Lab: Kombinasi Outfit")
st.write("Seorang siswa memiliki 4 kaos dan 3 celana.")
st.write("Berapa banyak cara yang mungkin untuk memilih 2 jenis pakaian berbeda (kaos dan celana)?")

st.header("1. Pilih Kaos dan Celana")

# Pilihan Kaos
st.subheader("Kaos")
kaos = {
    "Kaos Merah": "👕 Merah",
    "Kaos Biru": "👕 Biru",
    "Kaos Hijau": "👕 Hijau",
    "Kaos Kuning": "👕 Kuning"
}
selected_kaos = [nama for nama in kaos if st.checkbox(kaos[nama], key=nama)]

# Pilihan Celana
st.subheader("Celana")
celana = {
    "Celana Hitam": "👖 Hitam",
    "Celana Jeans": "👖 Jeans",
    "Celana Abu": "👖 Abu-abu"
}
selected_celana = [nama for nama in celana if st.checkbox(celana[nama], key=nama)]

# Tampilkan Kombinasi
st.header("2. Hasil Kombinasi yang Dipilih")

if selected_kaos and selected_celana:
    kombinasi = list(product(selected_kaos, selected_celana))
    for i, (k, c) in enumerate(kombinasi, 1):
        st.write(f"{i}. {kaos[k]} + {celana[c]}")
    st.success(f"Jumlah kombinasi: {len(kombinasi)}")
else:
    st.info("Pilih minimal satu kaos dan satu celana untuk melihat kombinasi.")

# Perbandingan dengan Rumus
st.header("3. Perbandingan dengan Rumus")

st.markdown("**Rumus kombinasi:** banyak kaos × banyak celana")

total_kaos = len(kaos)
total_celana = len(celana)
total_rumus = total_kaos * total_celana

st.write(f"Banyak kaos tersedia: {total_kaos}")
st.write(f"Banyak celana tersedia: {total_celana}")
st.write(f"Jumlah kombinasi menurut rumus: {total_rumus}")
