# -*- coding: utf-8 -*-
"""TES PSIKOLOG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypVgql4487o9WkVcNG-8R-LGvxIiAvkQ
"""

import streamlit as st

def run_personality_quiz_streamlit():
    """
    Menjalankan Kalkulator Kepribadian (Mini Tes Psikologi) sederhana
    menggunakan Streamlit.
    """
    st.title("Kalkulator Kepribadian Sederhana")
    st.subheader("(Mini Tes Psikologi)")
    st.write("---")
    st.write("Jawablah pertanyaan-pertanyaan berikut dengan jujur ya!\n")

    # Inisialisasi skor untuk setiap tipe kepribadian
    scores = {'Analitis': 0, 'Kreatif': 0, 'Sosial': 0, 'Praktis': 0}

    # Daftar pertanyaan dan opsi jawabannya
    questions = [
        {
            "question": "Ketika ada masalah yang rumit, kamu cenderung...",
            "options": {
                "a": "Menganalisis semua data dan mencari solusi logis yang paling efisien.",
                "b": "Mencari ide-ide baru dan pendekatan yang tidak biasa, bahkan jika itu sedikit berisiko.",
                "c": "Berdiskusi dengan banyak orang untuk mencari konsensus dan dukungan.",
                "d": "Langsung bertindak dan mencoba berbagai solusi cepat sampai menemukan yang berhasil."
            },
            "answers": {
                "a": 'Analitis',
                "b": 'Kreatif',
                "c": 'Sosial',
                "d": 'Praktis'
            }
        },
        {
            "question": "Di waktu luang, aktivitas yang paling menarik bagimu adalah...",
            "options": {
                "a": "Membaca buku, menonton dokumenter, atau belajar keterampilan baru yang menantang pikiran.",
                "b": "Melukis, menulis cerita, membuat musik, atau melakukan proyek seni lainnya.",
                "c": "Berkumpul dengan teman dan keluarga, bersosialisasi, atau terlibat dalam kegiatan komunitas.",
                "d": "Melakukan aktivitas fisik, mengerjakan proyek DIY (Do It Yourself), atau mengatur sesuatu agar lebih efisien."
            },
            "answers": {
                "a": 'Analitis',
                "b": 'Kreatif',
                "c": 'Sosial',
                "d": 'Praktis'
            }
        },
        {
            "question": "Dalam sebuah tim atau kelompok, peran favoritmu adalah...",
            "options": {
                "a": "Perencana strategis yang memastikan semua detail diperhitungkan.",
                "b": "Pencetus ide dan inovator yang selalu punya cara pandang baru.",
                "c": "Penengah dan pembangun hubungan, menjaga keharmonisan tim.",
                "d": "Pelaksana yang efisien dan memastikan pekerjaan selesai tepat waktu."
            },
            "answers": {
                "a": 'Analitis',
                "b": 'Kreatif',
                "c": 'Sosial',
                "d": 'Praktis'
            }
        },
        {
            "question": "Saat menghadapi perubahan mendadak, bagaimana reaksimu?",
            "options": {
                "a": "Mencoba memahami dampak perubahan secara rasional dan membuat rencana adaptasi.",
                "b": "Antusias dengan kemungkinan-kemungkinan baru dan peluang untuk berinovasi.",
                "c": "Beradaptasi dengan baik dan memastikan semua orang merasa nyaman dengan perubahan.",
                "d": "Siap menghadapi tantangan dan segera mencari cara praktis untuk melaluinya."
            },
            "answers": {
                "a": 'Analitis',
                "b": 'Kreatif',
                "c": 'Sosial',
                "d": 'Praktis'
            }
        },
        {
            "question": "Gaya belajarmu yang paling efektif adalah...",
            "options": {
                "a": "Melalui logika, pemikiran kritis, dan pemecahan masalah.",
                "b": "Melalui eksperimen, eksplorasi, dan menemukan hal-hal baru.",
                "c": "Melalui diskusi kelompok, interaksi sosial, dan berbagi ide.",
                "d": "Melalui praktik langsung, pengalaman nyata, dan mencoba sendiri."
            },
            "answers": {
                "a": 'Analitis',
                "b": 'Kreatif',
                "c": 'Sosial',
                "d": 'Praktis'
            }
        }
    ]

    # Menggunakan st.radio untuk pertanyaan pilihan ganda
    user_answers = {}
    for i, q in enumerate(questions):
        # Memformat opsi untuk st.radio agar lebih mudah dibaca
        options_list = [f"{key.upper()}. {value}" for key, value in q['options'].items()]
        # st.radio memberikan nilai yang dipilih (misal 'A. Pilihan Deskripsi')
        selected_option = st.radio(f"{i + 1}. {q['question']}", options_list, key=f"q{i}")
        # Ekstrak kunci jawaban (misal 'a', 'b', 'c', 'd') dari pilihan yang dipilih
        if selected_option: # Pastikan ada pilihan yang dibuat
            answer_key = selected_option[0].lower() # Ambil huruf pertama (a,b,c,d)
            user_answers[f"q{i}"] = answer_key # Simpan jawaban mentah

    st.write("---")

    # Tombol untuk melihat hasil
    if st.button("Lihat Hasil Kepribadian"):
        # Pastikan semua pertanyaan sudah dijawab sebelum menghitung skor
        if len(user_answers) == len(questions):
            # Hitung skor berdasarkan jawaban pengguna
            for i, q in enumerate(questions):
                answer_key = user_answers[f"q{i}"]
                if answer_key in q['answers']: # Verifikasi lagi jawaban valid
                    scores[q['answers'][answer_key]] += 1

            # Menentukan kepribadian utama (atau beberapa jika skornya sama)
            max_score = max(scores.values())
            dominant_personalities = [p for p, s in scores.items() if s == max_score]

            st.header("Hasil Kepribadianmu")
            st.write("---")

            if len(dominant_personalities) > 1:
                st.info("Kamu memiliki **kombinasi beberapa kepribadian dominan**:")
                for dp in dominant_personalities:
                    if dp == 'Analitis':
                        st.markdown(f"- **Analitis**: Kamu adalah pemikir logis dan rasional yang suka memecahkan masalah dengan data dan fakta.")
                    elif dp == 'Kreatif':
                        st.markdown(f"- **Kreatif**: Kamu adalah individu yang imajinatif, inovatif, dan selalu mencari cara baru untuk berekspresi.")
                    elif dp == 'Sosial':
                        st.markdown(f"- **Sosial**: Kamu adalah pribadi yang empatis, komunikatif, dan suka berinteraksi serta membantu orang lain.")
                    elif dp == 'Praktis':
                        st.markdown(f"- **Praktis**: Kamu adalah seseorang yang realistis, fokus pada hasil, dan lebih suka bertindak daripada berteori.")
                st.write("\n**Saran**: Manfaatkan kekuatan dari semua kepribadian dominanmu untuk meraih sukses!")
            elif len(dominant_personalities) == 1:
                main_personality = dominant_personalities[0]
                if main_personality == 'Analitis':
                    st.success("Kamu cenderung memiliki kepribadian yang **ANALITIS**.")
                    st.write("Ciri-ciri: Logis, detail, pemikir kritis, suka memecahkan masalah, dan selalu mencari kebenaran berdasarkan data.")
                    st.write("**Saran**: Teruslah kembangkan kemampuan analisismu dan gunakan untuk membuat keputusan yang tepat!")
                elif main_personality == 'Kreatif':
                    st.success("Kamu cenderung memiliki kepribadian yang **KREATIF**.")
                    st.write("Ciri-ciri: Inovatif, imajinatif, orisinal, suka menciptakan hal baru, dan melihat dunia dari berbagai perspektif.")
                    st.write("**Saran**: Jangan takut untuk mengekspresikan ide-idemu dan teruslah berkarya!")
                elif main_personality == 'Sosial':
                    st.success("Kamu cenderung memiliki kepribadian yang **SOSIAL**.")
                    st.write("Ciri-ciri: Empatis, kolaboratif, komunikatif, suka membantu orang lain, dan pandai membangun hubungan.")
                    st.write("**Saran**: Pertahankan hubungan baikmu dengan sesama dan jadilah jembatan antar individu!")
                elif main_personality == 'Praktis':
                    st.success("Kamu cenderung memiliki kepribadian yang **PRAKTIS**.")
                    st.write("Ciri-ciri: Realistis, terorganisir, fokus pada hasil, suka bertindak, dan mencari solusi yang efisien.")
                    st.write("**Saran**: Manfaatkan energimu untuk mencapai tujuan nyata dan jadilah pelaksana yang handal!")
            else:
                st.error("Maaf, terjadi kesalahan dalam perhitungan hasil. Mohon coba lagi.")

            st.write("---")
            st.write("Terima kasih sudah mencoba Kalkulator Kepribadian ini!")
        else:
            st.warning("Mohon jawab semua pertanyaan sebelum melihat hasil.")

# Panggil fungsi utama Streamlit
if __name__ == "__main__":
    run_personality_quiz_streamlit()