# -*- coding: utf-8 -*-
"""Tes Psikolog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvgBRRfVmWOU-wzJUF5plpVnZDR1XMNv
"""

def run_personality_quiz():
    """
    Menjalankan Kalkulator Kepribadian (Mini Tes Psikologi) sederhana.
    """
    print("====================================")
    print("  Kalkulator Kepribadian Sederhana  ")
    print("           (Mini Tes Psikologi)     ")
    print("====================================")
    print("\nJawablah pertanyaan-pertanyaan berikut dengan jujur ya!\n")

    # Inisialisasi skor untuk setiap tipe kepribadian (ini contoh, bisa disesuaikan)
    # Misal: A = Analitis, B = Kreatif, C = Sosial, D = Praktis
    scores = {'A': 0, 'B': 0, 'C': 0, 'D': 0}

    questions = [
        {
            "question": "Ketika ada masalah, kamu cenderung...",
            "options": {
                "a": "Menganalisis data dan mencari solusi logis.",
                "b": "Mencari ide-ide baru dan pendekatan yang tidak biasa.",
                "c": "Berdiskusi dengan orang lain dan mencari konsensus.",
                "d": "Langsung bertindak dan mencari solusi yang cepat."
            },
            "answers": {
                "a": 'A',
                "b": 'B',
                "c": 'C',
                "d": 'D'
            }
        },
        {
            "question": "Di waktu luang, kamu lebih suka...",
            "options": {
                "a": "Membaca buku atau belajar hal baru.",
                "b": "Melukis, menulis, atau melakukan kegiatan seni.",
                "c": "Berkumpul dengan teman atau keluarga.",
                "d": "Melakukan aktivitas fisik atau proyek praktis."
            },
            "answers": {
                "a": 'A',
                "b": 'B',
                "c": 'C',
                "d": 'D'
            }
        },
        {
            "question": "Dalam sebuah tim, peran favoritmu adalah...",
            "options": {
                "a": "Perencana dan pemecah masalah.",
                "b": "Pencetus ide dan inovator.",
                "c": "Penengah dan pembangun hubungan.",
                "d": "Pelaksana dan pengambil keputusan."
            },
            "answers": {
                "a": 'A',
                "b": 'B',
                "c": 'C',
                "d": 'D'
            }
        },
        {
            "question": "Saat menghadapi perubahan, kamu merasa...",
            "options": {
                "a": "Tertarik untuk memahami dampaknya secara detail.",
                "b": "Antusias dengan kemungkinan-kemungkinan baru.",
                "c": "Beradaptasi dengan baik dan menjaga keharmonisan.",
                "d": "Siap menghadapi tantangan dan menemukan jalan."
            },
            "answers": {
                "a": 'A',
                "b": 'B',
                "c": 'C',
                "d": 'D'
            }
        },
        {
            "question": "Gaya belajarmu yang paling efektif adalah...",
            "options": {
                "a": "Melalui logika dan pemikiran kritis.",
                "b": "Melalui eksperimen dan eksplorasi.",
                "c": "Melalui diskusi dan interaksi sosial.",
                "d": "Melalui praktik langsung dan pengalaman."
            },
            "answers": {
                "a": 'A',
                "b": 'B',
                "c": 'C',
                "d": 'D'
            }
        }
    ]

    for i, q in enumerate(questions):
        print(f"\n{i + 1}. {q['question']}")
        for key, value in q['options'].items():
            print(f"   {key}. {value}")

        while True:
            answer = input("Pilihanmu (a/b/c/d): ").lower()
            if answer in q['options']:
                scores[q['answers'][answer]] += 1
                break
            else:
                print("Pilihan tidak valid. Silakan pilih a, b, c, atau d.")

    # Menentukan kepribadian utama
    main_personality = max(scores, key=scores.get)

    print("\n====================================")
    print("         Hasil Kepribadianmu        ")
    print("====================================")

    if main_personality == 'A':
        print("\nKamu cenderung memiliki kepribadian yang ANALITIS.")
        print("Ciri-ciri: Logis, detail, pemikir kritis, suka memecahkan masalah.")
        print("Saran: Teruslah kembangkan kemampuan analisismu!")
    elif main_personality == 'B':
        print("\nKamu cenderung memiliki kepribadian yang KREATIF.")
        print("Ciri-ciri: Inovatif, imajinatif, orisinal, suka menciptakan hal baru.")
        print("Saran: Jangan takut untuk mengekspresikan ide-idemu!")
    elif main_personality == 'C':
        print("\nKamu cenderung memiliki kepribadian yang SOSIAL.")
        print("Ciri-ciri: Empatis, kolaboratif, komunikatif, suka membantu orang lain.")
        print("Saran: Pertahankan hubungan baikmu dengan sesama!")
    elif main_personality == 'D':
        print("\nKamu cenderung memiliki kepribadian yang PRAKTIS.")
        print("Ciri-ciri: Realistis, terorganisir, fokus pada hasil, suka bertindak.")
        print("Saran: Manfaatkan energimu untuk mencapai tujuan nyata!")
    else:
        print("\nAda yang salah dalam perhitungan hasil. Maaf ya!")

    print("\nTerima kasih sudah mencoba!")
    print("====================================")

# Panggil fungsi untuk menjalankan kuis
run_personality_quiz()